const express = require('express');
const Resource = require('../models/Resource');
const Quiz = require('../models/Quiz');
const PhaseArtifact = require('../models/PhaseArtifact');
const User = require('../models/User');
const Department = require('../models/Department');
const CollaborationComment = require('../models/CollaborationComment');
const ResourceVersion = require('../models/ResourceVersion');
const ResourceRating = require('../models/ResourceRating');
const ResourceShare = require('../models/ResourceShare');
const { requireAuth, requireRole } = require('../middleware/auth');
const { cleanText, writeAudit } = require('../services/security');
const { resourceSnapshot, applySnapshot, departmentMembership, canAccessResource, shareCode, qrSvgDataUrl, workloadFromData } = require('../services/collaboration');

const router = express.Router();

router.get('/public/:code', async (req,res,next)=>{
  try{
    const link=await ResourceShare.findOne({code:req.params.code,active:true}).populate({path:'resource',populate:{path:'owner',select:'name'}});
    if(!link||!link.resource||(link.expiresAt&&link.expiresAt<new Date())) return res.status(404).json({error:'This shared resource is unavailable or expired.'});
    link.views+=1; await link.save(); const r=link.resource;
    res.json({resource:{id:r._id,type:r.type,topic:r.topic,course:r.course,subject:r.subject,difficulty:r.difficulty,language:r.language,executiveSummary:r.executiveSummary,sections:r.sections,reportSections:r.reportSections,qa:r.qa,bloomQuestions:r.bloomQuestions,courseOutcomes:r.courseOutcomes,qualityScore:r.qualityScore,ratingAverage:r.ratingAverage,ratingCount:r.ratingCount,workflowStatus:r.workflowStatus,ownerName:r.owner?.name||'Faculty',updatedAt:r.updatedAt||r.createdAt},views:link.views});
  }catch(err){next(err)}
});

router.use(requireAuth);

async function getAccessible(req,id,options={}){const resource=await Resource.findById(id);if(!resource)return null;if(!(await canAccessResource(req.user,resource,options)))return false;return resource;}

router.get('/workload', requireRole('teacher','admin'), async (req,res,next)=>{try{const owner=req.user.role==='admin'&&req.query.scope==='all'?{}:{owner:req.user._id};const [resources,quizzes,artifacts]=await Promise.all([Resource.find(owner).lean(),Quiz.find(owner).lean(),PhaseArtifact.find(owner).lean()]);res.json({workload:workloadFromData(resources,quizzes,artifacts)});}catch(err){next(err)}});

router.get('/departments', async (req,res,next)=>{try{const q=req.user.role==='admin'?{}:{$or:[{owner:req.user._id},{'members.user':req.user._id}]};const departments=await Department.find(q).populate('owner','name email').populate('members.user','name email role').sort({name:1});res.json({departments});}catch(err){next(err)}});
router.post('/departments', requireRole('teacher','admin'), async (req,res,next)=>{try{const department=await Department.create({owner:req.user._id,name:cleanText(req.body?.name,140),code:cleanText(req.body?.code,30).toUpperCase(),description:cleanText(req.body?.description,1200),members:[{user:req.user._id,role:'reviewer'}]});await writeAudit({req,actor:req.user,action:'DEPARTMENT_CREATED',targetType:'Department',targetId:department._id});res.status(201).json({department});}catch(err){if(err.code===11000)return res.status(409).json({error:'That department code already exists for your account.'});next(err)}});
router.post('/departments/:id/members', requireRole('teacher','admin'), async (req,res,next)=>{try{const dept=await Department.findById(req.params.id);if(!dept)return res.status(404).json({error:'Department not found.'});if(req.user.role!=='admin'&&String(dept.owner)!==String(req.user._id))return res.status(403).json({error:'Only the department owner can add members.'});const user=await User.findOne({email:String(req.body?.email||'').trim().toLowerCase(),isActive:true});if(!user)return res.status(404).json({error:'No active user was found with that email.'});const role=req.body?.role==='reviewer'?'reviewer':'member';const existing=dept.members.find((x)=>String(x.user)===String(user._id));if(existing)existing.role=role;else dept.members.push({user:user._id,role});dept.updatedAt=new Date();await dept.save();res.json({department:await dept.populate('members.user','name email role')});}catch(err){next(err)}});

router.get('/department/:id/dashboard', async (req,res,next)=>{try{const membership=await departmentMembership(req.user._id,req.params.id);if(req.user.role!=='admin'&&!membership)return res.status(403).json({error:'Department access denied.'});const [dept,resources]=await Promise.all([Department.findById(req.params.id).populate('members.user','name email role'),Resource.find({department:req.params.id}).populate('owner','name email').sort({updatedAt:-1})]);const counts={total:resources.length,draft:0,in_review:0,approved:0,rejected:0};const subjects=new Map();resources.forEach((r)=>{counts[r.workflowStatus]=(counts[r.workflowStatus]||0)+1;if(r.subject)subjects.set(r.subject,(subjects.get(r.subject)||0)+1)});res.json({department:dept,counts,topSubjects:[...subjects.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([subject,count])=>({subject,count})),resources});}catch(err){next(err)}});
router.get('/department/:id/resources', async (req,res,next)=>{try{const membership=await departmentMembership(req.user._id,req.params.id);if(req.user.role!=='admin'&&!membership)return res.status(403).json({error:'Department access denied.'});res.json({resources:await Resource.find({department:req.params.id}).populate('owner','name email').sort({updatedAt:-1})});}catch(err){next(err)}});

router.patch('/resources/:id/department', requireRole('teacher','admin'), async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id,{write:true});if(resource===null)return res.status(404).json({error:'Resource not found.'});if(resource===false)return res.status(403).json({error:'Resource access denied.'});const dept=await Department.findById(req.body?.departmentId);if(!dept)return res.status(404).json({error:'Department not found.'});const membership=await departmentMembership(req.user._id,dept._id);if(req.user.role!=='admin'&&!membership)return res.status(403).json({error:'You are not a member of this department.'});resource.department=dept._id;resource.folderName=cleanText(req.body?.folderName||'General',120);resource.updatedAt=new Date();if(!dept.folders.includes(resource.folderName)){dept.folders.push(resource.folderName);dept.updatedAt=new Date();await dept.save();}await resource.save();res.json({resource});}catch(err){next(err)}});

router.get('/resources/:id/comments', async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id);if(resource===null)return res.status(404).json({error:'Resource not found.'});if(resource===false)return res.status(403).json({error:'Resource access denied.'});const comments=await CollaborationComment.find({resource:resource._id}).populate('author','name email role').sort({createdAt:1});res.json({comments});}catch(err){next(err)}});
router.post('/resources/:id/comments', async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id,{write:true});if(resource===null)return res.status(404).json({error:'Resource not found.'});if(resource===false)return res.status(403).json({error:'Resource access denied.'});const message=cleanText(req.body?.message,3000);if(!message)return res.status(400).json({error:'Comment cannot be empty.'});const type=['comment','review','change-request','approval-note'].includes(req.body?.type)?req.body.type:'comment';const comment=await CollaborationComment.create({resource:resource._id,author:req.user._id,message,type});await writeAudit({req,actor:req.user,action:'RESOURCE_COMMENT_ADDED',targetType:'Resource',targetId:resource._id,metadata:{type}});res.status(201).json({comment:await comment.populate('author','name email role')});}catch(err){next(err)}});

router.get('/resources/:id/versions', async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id);if(resource===null)return res.status(404).json({error:'Resource not found.'});if(resource===false)return res.status(403).json({error:'Resource access denied.'});res.json({versions:await ResourceVersion.find({resource:resource._id}).populate('createdBy','name email').sort({versionNumber:-1})});}catch(err){next(err)}});
router.post('/resources/:id/versions', requireRole('teacher','admin'), async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id,{write:true});if(!resource)return res.status(resource===null?404:403).json({error:resource===null?'Resource not found.':'Resource access denied.'});const latest=await ResourceVersion.findOne({resource:resource._id}).sort({versionNumber:-1});const versionNumber=(latest?.versionNumber||0)+1;const version=await ResourceVersion.create({resource:resource._id,versionNumber,label:cleanText(req.body?.label||`Version ${versionNumber}`,100),note:cleanText(req.body?.note,1000),createdBy:req.user._id,snapshot:resourceSnapshot(resource)});resource.currentVersion=versionNumber;resource.updatedAt=new Date();await resource.save();res.status(201).json({version});}catch(err){next(err)}});
router.post('/resources/:id/versions/:version/restore', requireRole('teacher','admin'), async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id,{write:true});if(!resource)return res.status(resource===null?404:403).json({error:resource===null?'Resource not found.':'Resource access denied.'});const version=await ResourceVersion.findOne({resource:resource._id,versionNumber:Number(req.params.version)});if(!version)return res.status(404).json({error:'Version not found.'});applySnapshot(resource,version.snapshot);const latest=await ResourceVersion.findOne({resource:resource._id}).sort({versionNumber:-1});const newNum=(latest?.versionNumber||0)+1;await ResourceVersion.create({resource:resource._id,versionNumber:newNum,label:`Restored from Version ${version.versionNumber}`,note:cleanText(req.body?.note,1000),createdBy:req.user._id,snapshot:resourceSnapshot(resource)});resource.currentVersion=newNum;await resource.save();res.json({resource,restoredFrom:version.versionNumber,newVersion:newNum});}catch(err){next(err)}});

router.post('/resources/:id/workflow', requireRole('teacher','admin'), async (req,res,next)=>{try{const resource=await Resource.findById(req.params.id);if(!resource)return res.status(404).json({error:'Resource not found.'});const action=req.body?.action;const note=cleanText(req.body?.note,2000);const owner=String(resource.owner)===String(req.user._id);const canWrite=await canAccessResource(req.user,resource,{write:true});const canReview=req.user.role==='admin'||Boolean(await canAccessResource(req.user,resource,{review:true}));if(action==='submit'&&canWrite){resource.workflowStatus='in_review';resource.submittedForReviewAt=new Date();}
else if(action==='approve'&&canReview){resource.workflowStatus='approved';resource.reviewedBy=req.user._id;resource.reviewedAt=new Date();resource.reviewNote=note;}
else if(action==='reject'&&canReview){resource.workflowStatus='rejected';resource.reviewedBy=req.user._id;resource.reviewedAt=new Date();resource.reviewNote=note;}
else if(action==='reopen'&&(owner||req.user.role==='admin')){resource.workflowStatus='draft';resource.reviewedBy=null;resource.reviewedAt=null;resource.reviewNote=note;}
else return res.status(403).json({error:'This workflow action is not allowed.'});resource.workflowHistory.push({action,by:req.user._id,note,at:new Date()});resource.updatedAt=new Date();await resource.save();if(action==='approve'){const latest=await ResourceVersion.findOne({resource:resource._id}).sort({versionNumber:-1});const n=(latest?.versionNumber||0)+1;await ResourceVersion.create({resource:resource._id,versionNumber:n,label:'Final Approved Version',note,createdBy:req.user._id,snapshot:resourceSnapshot(resource)});resource.currentVersion=n;await resource.save();}await writeAudit({req,actor:req.user,action:`RESOURCE_${String(action).toUpperCase()}`,targetType:'Resource',targetId:resource._id,metadata:{note}});res.json({resource});}catch(err){next(err)}});
router.get('/review-queue', requireRole('teacher','admin'), async (req,res,next)=>{try{let query={workflowStatus:'in_review'};if(req.user.role!=='admin'){const depts=await Department.find({$or:[{owner:req.user._id},{members:{$elemMatch:{user:req.user._id,role:'reviewer'}}}]}).select('_id');query.department={$in:depts.map((d)=>d._id)}}res.json({resources:await Resource.find(query).populate('owner','name email').populate('department','name code').sort({submittedForReviewAt:1})});}catch(err){next(err)}});

router.post('/resources/:id/rating', async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id);if(!resource)return res.status(resource===null?404:403).json({error:resource===null?'Resource not found.':'Resource access denied.'});const rating=Math.max(1,Math.min(5,Number(req.body?.rating||0)));const tag=['Useful','Needs edit','Best for exam','Best for class explanation','Well researched'].includes(req.body?.tag)?req.body.tag:'Useful';await ResourceRating.findOneAndUpdate({resource:resource._id,user:req.user._id},{rating,tag,review:cleanText(req.body?.review,1000),updatedAt:new Date()},{upsert:true,new:true,setDefaultsOnInsert:true});const agg=await ResourceRating.aggregate([{$match:{resource:resource._id}},{$group:{_id:'$resource',average:{$avg:'$rating'},count:{$sum:1}}}]);resource.ratingAverage=Math.round((agg[0]?.average||0)*10)/10;resource.ratingCount=agg[0]?.count||0;await resource.save();res.json({ratingAverage:resource.ratingAverage,ratingCount:resource.ratingCount});}catch(err){next(err)}});
router.get('/resources/:id/ratings', async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id);if(!resource)return res.status(resource===null?404:403).json({error:resource===null?'Resource not found.':'Resource access denied.'});const ratings=await ResourceRating.find({resource:resource._id}).populate('user','name role').sort({updatedAt:-1}).limit(100);res.json({ratings,average:resource.ratingAverage,count:resource.ratingCount});}catch(err){next(err)}});

router.post('/resources/:id/share-link', requireRole('teacher','admin'), async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id,{write:true});if(!resource)return res.status(resource===null?404:403).json({error:resource===null?'Resource not found.':'Resource access denied.'});if(resource.workflowStatus!=='approved')return res.status(409).json({error:'Approve the resource before creating a public QR share link.'});let link=await ResourceShare.findOne({resource:resource._id});if(!link)link=await ResourceShare.create({resource:resource._id,code:shareCode(),createdBy:req.user._id});else{link.active=true;if(req.body?.regenerate)link.code=shareCode();await link.save();}resource.publicShareEnabled=true;await resource.save();const base=(process.env.PUBLIC_BASE_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'');const publicUrl=`${base}/public-share.html?code=${encodeURIComponent(link.code)}`;const qrDataUrl=qrSvgDataUrl(publicUrl,{margin:4});res.json({code:link.code,publicUrl,qrDataUrl,views:link.views});}catch(err){next(err)}});
router.delete('/resources/:id/share-link', requireRole('teacher','admin'), async (req,res,next)=>{try{const resource=await getAccessible(req,req.params.id,{write:true});if(!resource)return res.status(resource===null?404:403).json({error:resource===null?'Resource not found.':'Resource access denied.'});await ResourceShare.updateOne({resource:resource._id},{$set:{active:false}});resource.publicShareEnabled=false;await resource.save();res.json({ok:true});}catch(err){next(err)}});

module.exports=router;
