const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const Quiz = require(path.join(root, 'models', 'Quiz'));
const QuizAttempt = require(path.join(root, 'models', 'QuizAttempt'));
const quizModel = fs.readFileSync(path.join(root, 'models', 'Quiz.js'), 'utf8');
const attemptModel = fs.readFileSync(path.join(root, 'models', 'QuizAttempt.js'), 'utf8');
const routes = fs.readFileSync(path.join(root, 'routes', 'quizzes.js'), 'utf8');
const resourcesRoute = fs.readFileSync(path.join(root, 'routes', 'resources.js'), 'utf8');
const syllabusRoute = fs.readFileSync(path.join(root, 'routes', 'syllabus.js'), 'utf8');
const mediaRoute = fs.readFileSync(path.join(root, 'routes', 'media.js'), 'utf8');
const modal = fs.readFileSync(path.join(root, '..', 'frontend', 'js', 'modal.js'), 'utf8');
const quizUi = fs.readFileSync(path.join(root, '..', 'frontend', 'js', 'quizzes.js'), 'utf8');
assert(quizModel.includes('integrityPolicySchema'));
assert(attemptModel.includes("'cancelled'"));
assert(routes.includes("router.post('/:id/integrity'"));
assert(routes.includes('camera_permission_revoked'));
assert(resourcesRoute.includes("router.get('/:id'"));
assert(syllabusRoute.includes("'%PDF-'"));
assert(mediaRoute.includes('single-extension') || mediaRoute.includes('double-extension'));
assert(modal.includes('apiGetResource'));
assert(quizUi.includes('getUserMedia'));
assert(quizUi.includes('visibilitychange'));
assert(quizUi.includes('requestFullscreen'));
assert(quizUi.includes('camera_obstructed'));
const quiz = new Quiz({ owner: '64b64c000000000000000001', title: 'Secure Quiz', questions: [{ prompt: 'Q?', correctAnswer: 'A' }] });
assert.strictEqual(quiz.integrityPolicy.requireCamera, true);
assert.strictEqual(quiz.integrityPolicy.requireFullscreen, true);
const attempt = new QuizAttempt({ quiz: '64b64c000000000000000002', student: '64b64c000000000000000003', status: 'cancelled', expiresAt: new Date(Date.now()+60000), attemptTokenHash: 'a'.repeat(64), submissionNonceHash: 'b'.repeat(64), deviceFingerprintHash: 'c'.repeat(64) });
assert.strictEqual(attempt.status, 'cancelled');
console.log('Secure quiz, upload restrictions and resource-view smoke checks passed.');
process.exit(0);
