function draftToText(draft) {
  let out = `${String(draft.type || '').toUpperCase()}: ${draft.topic}\n`;
  out += `Course: ${draft.course} | Subject: ${draft.subject} | Difficulty: ${draft.difficulty} | Duration: ${draft.duration}`;
  out += draft.language && draft.language !== 'English' ? ` | Language: ${draft.language}\n` : '\n';
  out += `Explanation style: ${draft.style || 'Concept-First'}\n`;
  if (draft.syllabusName) out += `Academic sources: ${draft.syllabusName}\n`;
  if (draft.contentDepth) out += `Depth: ${draft.contentDepth} | Visual density: ${draft.visualDensity || 'balanced'}\n`;
  out += 'Generated by AI Teacher Resource Hub (AI-assisted, teacher-reviewed draft)\n';
  out += `${'='.repeat(70)}\n\n`;

  if (draft.executiveSummary) out += `EXECUTIVE SUMMARY\n${'-'.repeat(22)}\n${draft.executiveSummary}\n\n`;

  if (draft.reportSections && draft.reportSections.length) {
    draft.reportSections.forEach((section, sectionIndex) => {
      out += `${sectionIndex + 1}. ${section.heading}\n${'-'.repeat(Math.min(70, String(section.heading || '').length + 4))}\n`;
      if (section.summary) out += `${section.summary}\n\n`;
      (section.explanation || []).forEach((paragraph) => { out += `${paragraph}\n\n`; });
      if ((section.keyPoints || []).length) out += `Key Points:\n${section.keyPoints.map((x) => `- ${x}`).join('\n')}\n\n`;
      if ((section.examples || []).length) out += `Examples:\n${section.examples.map((x) => `- ${x.title}: ${x.description}`).join('\n')}\n\n`;
      if ((section.applications || []).length) out += `Applications:\n${section.applications.map((x) => `- ${x}`).join('\n')}\n\n`;
      if (section.caseStudy) out += `Case Study - ${section.caseStudy.title}:\n${section.caseStudy.description}\n\n`;
      if (section.table) {
        out += `Table: ${(section.table.headers || []).join(' | ')}\n`;
        (section.table.rows || []).forEach((row) => { out += `${row.join(' | ')}\n`; });
        out += '\n';
      }
      if (section.visual && section.visual.type !== 'none') out += `Visual: ${section.visual.title || section.visual.type}\n${section.visual.description || ''}\n${section.visual.caption || ''}\n\n`;
      if ((section.commonMistakes || []).length) out += `Common Mistakes:\n${section.commonMistakes.map((x) => `- ${x}`).join('\n')}\n\n`;
      if ((section.citations || []).length) out += `Citations: ${section.citations.join(', ')}\n\n`;
      if (section.speakerNotes) out += `Speaker Notes:\n${section.speakerNotes}\n\n`;
    });
  } else if (draft.sections) {
    draft.sections.forEach((s) => { out += `${s.h}\n${'-'.repeat(String(s.h || '').length)}\n${s.b}\n\n`; });
  } else if (draft.qa) draft.qa.forEach((item) => { out += `${item.q}\n${item.a}\n\n`; });

  if (draft.qualityScore) {
    out += `\nAI QUALITY SCORE\n${'-'.repeat(20)}\n`;
    out += `${draft.qualityScore.overall || 0}/100 - ${draft.qualityScore.grade || ''}\n`;
    const metrics = draft.qualityScore.metrics || {};
    Object.entries(metrics).forEach(([key, value]) => { out += `${key}: ${value}%\n`; });
    out += '\n';
  }

  if (draft.validationReport) {
    out += `\nEXPORT VALIDATION\n${'-'.repeat(22)}\n${draft.validationReport.score || 0}/100 - ${draft.validationReport.grade || ''}\n`;
    (draft.validationReport.checks || []).forEach((check) => { out += `${check.passed ? '[PASS]' : '[REVIEW]'} ${check.label}: ${check.detail}\n`; });
  }

  if (draft.bloomQuestions && draft.bloomQuestions.length) {
    out += `\nBLOOM'S TAXONOMY QUESTIONS\n${'-'.repeat(30)}\n`;
    draft.bloomQuestions.forEach((item, index) => {
      out += `${index + 1}. [${item.level}] ${item.question}\nAnswer: ${item.answer}\n${item.rationale ? `Rationale: ${item.rationale}\n` : ''}\n`;
    });
  }

  if (draft.courseOutcomes && draft.courseOutcomes.length) {
    out += `\nCOURSE OUTCOMES\n${'-'.repeat(20)}\n`;
    draft.courseOutcomes.forEach((item) => { out += `${item.code}: ${item.text}\n`; });
  }

  if (draft.coMapping && draft.coMapping.length) {
    out += `\nCOURSE OUTCOME MAPPING\n${'-'.repeat(26)}\n`;
    draft.coMapping.forEach((item) => {
      out += `${item.courseOutcome} -> ${(item.matchedSections || []).join(', ')}\nBloom: ${(item.bloomLevels || []).join(', ')} | Alignment: ${item.alignmentScore || 0}%\n${item.justification || ''}\n\n`;
    });
  }

  if (draft.references && draft.references.length) {
    out += `\nREFERENCES\n${'-'.repeat(16)}\n`;
    draft.references.forEach((ref) => { out += `[${ref.id}] ${ref.title}${ref.location ? ` - ${ref.location}` : ''}\n`; });
  } else if (draft.grounding && draft.grounding.retrievedChunks && draft.grounding.retrievedChunks.length) {
    out += `\nSYLLABUS EVIDENCE\n${'-'.repeat(20)}\n`;
    draft.grounding.retrievedChunks.forEach((source) => { out += `[${source.sourceId}] ${source.preview}\n`; });
  }
  return out;
}
function downloadText(draft) {
  triggerDownload(new Blob([draftToText(draft)], { type: 'text/plain' }), `${safeFileName(draft)}.txt`);
}

function downloadLMS(draft) {
  const color = TYPE_COLORS[draft.type] || '#2F5D50';
  let bodyHtml = '';
  if (draft.reportSections && draft.reportSections.length) bodyHtml = draft.reportSections.map((section, index) => `
    <section style="margin:34px 0;padding:24px;border:1px solid #d8dee9;border-radius:16px;background:#fff">
      <div style="color:#687386;font-size:12px;font-weight:700">SECTION ${index + 1}</div>
      <h2 style="color:${color};margin:5px 0 12px">${escapeHtml(section.heading)}</h2>
      ${section.summary ? `<p style="font-size:17px;color:#475569"><b>${escapeHtml(section.summary)}</b></p>` : ''}
      ${(section.explanation || []).map((p) => `<p>${escapeHtml(p)}</p>`).join('')}
      ${(section.keyPoints || []).length ? `<h3>Key Points</h3><ul>${section.keyPoints.map((x) => `<li>${escapeHtml(x)}</li>`).join('')}</ul>` : ''}
      ${(section.examples || []).length ? `<h3>Examples</h3>${section.examples.map((x) => `<div style="padding:12px;margin:10px 0;background:#eef6ff;border-left:4px solid ${color}"><b>${escapeHtml(x.title)}</b><p>${escapeHtml(x.description)}</p></div>`).join('')}` : ''}
      ${section.caseStudy ? `<h3>Case Study: ${escapeHtml(section.caseStudy.title)}</h3><p style="padding:14px;background:#fff7ed;border-radius:10px">${escapeHtml(section.caseStudy.description)}</p>` : ''}
      ${section.table ? `<table style="width:100%;border-collapse:collapse;margin:16px 0"><thead><tr>${section.table.headers.map((h) => `<th style="border:1px solid #cbd5e1;padding:9px;background:${color};color:white">${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${section.table.rows.map((row) => `<tr>${row.map((c) => `<td style="border:1px solid #cbd5e1;padding:9px">${escapeHtml(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>` : ''}
      ${section.visual && section.visual.type !== 'none' ? `<figure style="padding:18px;background:#f8fafc;border:1px dashed #94a3b8;border-radius:12px"><b>${escapeHtml(section.visual.title || 'Concept Visual')}</b><p>${escapeHtml(section.visual.description || '')}</p><figcaption>${escapeHtml(section.visual.caption || '')}</figcaption></figure>` : ''}
      ${(section.commonMistakes || []).length ? `<h3>Common Mistakes</h3><ul>${section.commonMistakes.map((x) => `<li>${escapeHtml(x)}</li>`).join('')}</ul>` : ''}
      ${(section.citations || []).length ? `<p style="font-size:12px;color:#64748b"><b>Citations:</b> ${escapeHtml(section.citations.join(', '))}</p>` : ''}
    </section>`).join('');
  else if (draft.sections) bodyHtml = draft.sections.map((s) => `<h3 style="color:${color};">${escapeHtml(s.h)}</h3><p style="white-space:pre-line">${escapeHtml(s.b)}</p>`).join('');
  else if (draft.qa) bodyHtml = draft.qa.map((item) => `<p><b>${escapeHtml(item.q)}</b><br>${escapeHtml(item.a)}</p>`).join('');

  const qualityHtml = draft.qualityScore ? `
    <section style="margin-top:32px;padding:20px;border-radius:12px;background:#eef7f3">
      <h2>AI Quality Score: ${Number(draft.qualityScore.overall || 0)}/100</h2>
      <p>${escapeHtml(draft.qualityScore.grade || '')} · Teacher review required</p>
    </section>` : '';
  const bloomHtml = draft.bloomQuestions && draft.bloomQuestions.length ? `
    <section style="margin-top:32px"><h2>Bloom's Taxonomy Questions</h2>${draft.bloomQuestions.map((item) => `<article style="border:1px solid #ddd;padding:14px;margin:10px 0;border-radius:8px"><b>${escapeHtml(item.level)}:</b> ${escapeHtml(item.question)}<p><i>Answer:</i> ${escapeHtml(item.answer)}</p></article>`).join('')}</section>` : '';
  const coHtml = draft.courseOutcomes && draft.courseOutcomes.length ? `
    <section style="margin-top:32px"><h2>Course Outcomes</h2><ul>${draft.courseOutcomes.map((item) => `<li><b>${escapeHtml(item.code)}</b>: ${escapeHtml(item.text)}</li>`).join('')}</ul></section>` : '';

  const html = [
    '<!DOCTYPE html><html><head><meta charset="utf-8"><title>', escapeHtml(draft.topic), '</title></head>',
    '<body style="font-family:Arial,sans-serif;max-width:840px;margin:40px auto;color:#222;line-height:1.65">',
    '<div style="background:', color, ';color:white;padding:18px 22px;border-radius:12px">',
    '<div style="font-size:11px;text-transform:uppercase;letter-spacing:.05em">', escapeHtml(draft.type), '</div>',
    '<h1 style="margin:6px 0 0;font-size:25px">', escapeHtml(draft.topic), '</h1></div>',
    '<p style="color:#666;font-size:13px">', escapeHtml(draft.course), ' | ', escapeHtml(draft.subject), ' | ', escapeHtml(draft.difficulty), ' | ', escapeHtml(draft.duration), '</p>',
    draft.syllabusName ? `<p><b>Academic sources:</b> ${escapeHtml(draft.syllabusName)}</p>` : '',
    draft.executiveSummary ? `<section style="padding:20px;background:#eef6ff;border-radius:12px"><h2>Executive Summary</h2><p>${escapeHtml(draft.executiveSummary)}</p></section>` : '',
    bodyHtml, qualityHtml, bloomHtml, coHtml,
    draft.references?.length ? `<section style="margin-top:32px"><h2>References</h2><ol>${draft.references.map((r) => `<li><b>[${escapeHtml(r.id)}]</b> ${escapeHtml(r.title)} ${r.location ? `— ${escapeHtml(r.location)}` : ''}</li>`).join('')}</ol></section>` : '',
    '<p style="margin-top:36px;color:#888;font-size:12px"><i>AI-assisted draft. Faculty review required before classroom use.</i></p>',
    '</body></html>'
  ].join('');
  triggerDownload(new Blob([html], { type: 'text/html' }), `${safeFileName(draft)}_lms.html`);
}

async function downloadPDF(draft) {
  try {
    const resp = await authFetch('/api/export/pdf', { method: 'POST', body: JSON.stringify({ draft }) });
    if (!resp.ok) {
      const err = await resp.json().catch(() => ({}));
      throw new Error(err.error || `Server error (${resp.status})`);
    }
    triggerDownload(await resp.blob(), `${safeFileName(draft)}.pdf`);
  } catch (err) {
    console.error(err);
    alert('Could not create the PDF: ' + err.message);
  }
}

async function downloadDOCX(draft) {
  try {
    const resp = await authFetch('/api/export/docx', { method: 'POST', body: JSON.stringify({ draft }) });
    if (!resp.ok) {
      const err = await resp.json().catch(() => ({}));
      throw new Error(err.error || `Server error (${resp.status})`);
    }
    triggerDownload(await resp.blob(), `${safeFileName(draft)}.docx`);
  } catch (err) {
    console.error(err);
    alert('Could not create the Word document: ' + err.message);
  }
}
