let p10Loaded=false,p10VoiceOutput=null;
function p10ResourceOptions(){['p10-resource','p10-safety-resource'].forEach(id=>{const s=document.getElementById(id);if(!s)return;const cur=s.value;s.innerHTML='<option value="">Use custom text/topic</option>'+resources.map(r=>`<option value="${r._id}">${escapeHtml(r.subject)} · ${escapeHtml(r.topic)}</option>`).join('');if([...s.options].some(o=>o.value===cur))s.value=cur;});const fs=document.getElementById('p10-fact-syllabus');if(fs){const cur=fs.value;fs.innerHTML='<option value="">Select indexed syllabus</option>'+syllabi.map(x=>`<option value="${x._id}">${escapeHtml(x.originalName)} · ${escapeHtml(x.subject||'')}</option>`).join('');if([...fs.options].some(o=>o.value===cur))fs.value=cur;}}
function p10out(html){document.getElementById('p10-output').innerHTML=html;window.runMotionEntrance&&window.runMotionEntrance(document.getElementById('p10-output'));}
function p10status(msg,error=false){const e=document.getElementById('p10-status');e.textContent=msg;e.classList.toggle('error',error)}
function renderVoice(o){p10VoiceOutput=o;p10out(`<div class="p10-result-head"><div><span>Voice Studio</span><h2>${escapeHtml(o.title)}</h2></div><b>${escapeHtml(o.generationMode||'generated')}</b></div><div class="p10-transcript">${escapeHtml(o.transcript)}</div><div class="p10-actions"><button id="p10-play" class="secondary-ai-btn">▶ Browser playback</button><button id="p10-stop" class="secondary-ai-btn">■ Stop</button><button id="p10-audio" class="gen-btn">Download AI audio (.wav)</button></div>`);document.getElementById('p10-play').onclick=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(o.transcript);u.lang=document.getElementById('p10-language').value==='Hindi'?'hi-IN':'en-IN';speechSynthesis.speak(u)};document.getElementById('p10-stop').onclick=()=>speechSynthesis.cancel();document.getElementById('p10-audio').onclick=async()=>{try{p10status('Generating downloadable Gemini TTS audio…');const blob=await apiP10Audio({text:o.transcript,voice:document.getElementById('p10-voice').value,filename:o.title});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(o.title||'voice-note').replace(/[^a-z0-9]+/gi,'-')+'.wav';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);p10status('Audio downloaded.');}catch(e){p10status(e.message,true)}};}
function renderVideo(o){p10out(`<div class="p10-result-head"><div><span>Video Script</span><h2>${escapeHtml(o.title)}</h2></div><b>${escapeHtml(o.format)}</b></div><div class="p10-hook">Hook: ${escapeHtml(o.hook)}</div><div class="p10-scene-grid">${(o.scenes||[]).map(s=>`<article><span>${s.scene}</span><h3>${escapeHtml(s.visual)}</h3><p>${escapeHtml(s.narration)}</p><small>${s.durationSeconds}s · ${escapeHtml(s.onScreenText)}</small></article>`).join('')}</div><div class="phase78-suggestions"><h3>Call to action</h3><p>${escapeHtml(o.cta)}</p></div>`);}
// Phase 11.35: Export Everywhere — client-side SVG → PNG (no server round trip;
// works entirely in the browser via canvas).
function svgToPngDownload(svgString, filename) {
  const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);
  const img = new Image();
  img.onload = () => {
    const scale = 2; // export at 2x for crisper PNGs
    const canvas = document.createElement('canvas');
    canvas.width = img.width * scale;
    canvas.height = img.height * scale;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.scale(scale, scale);
    ctx.drawImage(img, 0, 0);
    URL.revokeObjectURL(url);
    canvas.toBlob((blob) => {
      const pngUrl = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = pngUrl; a.download = filename;
      document.body.appendChild(a); a.click(); a.remove();
      URL.revokeObjectURL(pngUrl);
    }, 'image/png');
  };
  img.onerror = () => { URL.revokeObjectURL(url); showToast('Could not convert to PNG.', 'error'); };
  img.src = url;
}

function renderDiagram(d){const encoded='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(d.svg);p10out(`<div class="p10-result-head"><div><span>Diagram Studio</span><h2>${escapeHtml(d.plan.title)}</h2></div><b>${escapeHtml(d.plan.generationMode)}</b></div><div class="p10-svg">${d.svg}</div><a class="gen-btn p10-download" download="${escapeHtml(d.plan.title).replace(/[^a-z0-9]+/gi,'-')}.svg" href="${encoded}">Download SVG</a><button class="gen-btn p10-download" data-png style="background:transparent;border:1px solid #ccc;margin-left:8px;">Download PNG</button>`);document.querySelector('[data-png]')?.addEventListener('click',()=>svgToPngDownload(d.svg,`${d.plan.title.replace(/[^a-z0-9]+/gi,'-')}.png`));}
function renderChart(d){const encoded='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(d.svg);p10out(`<div class="p10-result-head"><div><span>Chart Studio</span><h2>${escapeHtml(d.plan.title)}</h2></div><b>${escapeHtml(d.plan.generationMode)}</b></div><div class="p10-svg">${d.svg}</div><a class="gen-btn p10-download" download="${escapeHtml(d.plan.title).replace(/[^a-z0-9]+/gi,'-')}.svg" href="${encoded}">Download SVG</a><button class="gen-btn p10-download" data-png style="background:transparent;border:1px solid #ccc;margin-left:8px;">Download PNG</button>`);document.querySelector('[data-png]')?.addEventListener('click',()=>svgToPngDownload(d.svg,`${d.plan.title.replace(/[^a-z0-9]+/gi,'-')}.png`));}
function renderWebSearch(d){
  const items=(d.results||[]).map(r=>`<div class="qws-result"><a href="${escapeHtml(r.url)}" target="_blank" rel="noopener"><b>${escapeHtml(r.title)}</b></a><p>${escapeHtml(r.snippet)}</p><span>${escapeHtml(r.source)}</span></div>`).join('');
  p10out(`<div class="p10-result-head"><div><span>Internet Search</span><h2>${d.results?.length||0} result(s)</h2></div><b>${escapeHtml(d.source||'Wikipedia')}</b></div>${items||'<p>No results found.</p>'}`);
}
function renderImageResults(d, label){
  const items=(d.results||[]).map(r=>`<div class="qimg-card"><img src="${escapeHtml(r.thumbUrl)}" alt="${escapeHtml(r.title)}" loading="lazy"><b>${escapeHtml(r.title)}</b><span>${escapeHtml(r.license)} · ${escapeHtml(r.artist)}</span><a href="${escapeHtml(r.pageUrl)}" target="_blank" rel="noopener">Source ↗</a></div>`).join('');
  p10out(`<div class="p10-result-head"><div><span>${escapeHtml(label)}</span><h2>${d.results?.length||0} result(s)</h2></div><b>${escapeHtml(d.source||'Wikimedia Commons')}</b></div><div class="qimg-grid">${items||'<p>No results found.</p>'}</div><p class="qimg-note">Free, openly-licensed images from Wikimedia Commons — check each license before reuse. (Not AI-generated images — this project doesn't have a paid image-generation API configured.)</p>`);
}
function renderInfographic(d){const encoded='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(d.svg);p10out(`<div class="p10-result-head"><div><span>Infographic Studio</span><h2>${escapeHtml(d.plan.title)}</h2></div><b>${escapeHtml(d.plan.generationMode)}</b></div><div class="p10-svg">${d.svg}</div><a class="gen-btn p10-download" download="${escapeHtml(d.plan.title).replace(/[^a-z0-9]+/gi,'-')}.svg" href="${encoded}">Download SVG</a><button class="gen-btn p10-download" data-png style="background:transparent;border:1px solid #ccc;margin-left:8px;">Download PNG</button>`);document.querySelector('[data-png]')?.addEventListener('click',()=>svgToPngDownload(d.svg,`${d.plan.title.replace(/[^a-z0-9]+/gi,'-')}.png`));}
function renderSmartTable(d){
  const plan=d.plan;
  const highlightByRow=new Map((plan.highlights||[]).map(h=>[h.rowIndex,h]));
  const theadHtml=`<tr>${plan.headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr>`;
  const rowsHtml=plan.rows.map((row,i)=>{
    const hl=highlightByRow.get(i);
    const cls=hl?` class="qst-row-${hl.color}"`:'';
    const cells=row.map(c=>`<td>${escapeHtml(c)}</td>`).join('');
    const reasonCell=hl?`<td class="qst-reason">⚑ ${escapeHtml(hl.reason||'Highlighted')}</td>`:'<td></td>';
    return `<tr${cls}>${cells}${reasonCell}</tr>`;
  }).join('');
  const csv=[plan.headers.join(','),...plan.rows.map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(','))].join('\n');
  const csvEncoded='data:text/csv;charset=utf-8,'+encodeURIComponent(csv);
  p10out(`<div class="p10-result-head"><div><span>Smart Table Studio</span><h2>${escapeHtml(plan.title)}</h2></div><b>${escapeHtml(plan.generationMode)}</b></div><div class="qst-table-wrap"><table class="qst-table"><thead>${theadHtml.replace('</tr>','<th>Highlight reason</th></tr>')}</thead><tbody>${rowsHtml}</tbody></table></div><a class="gen-btn p10-download" download="${escapeHtml(plan.title).replace(/[^a-z0-9]+/gi,'-')}.csv" href="${csvEncoded}">Download CSV</a>`);
}
function renderRisk(r){p10out(`<div class="p10-result-head"><div><span>Originality Risk</span><h2>${escapeHtml(r.label)}</h2></div><b class="risk-${r.riskLevel.toLowerCase()}">${r.riskLevel} · ${r.riskScore}/100</b></div><div class="p9-mini-stats"><b>${r.aiGeneratedLikelihood.score}%<small>AI-writing heuristic</small></b><b>${r.repetitiveContent.repeatedSentenceOpenings}<small>Repeated openings</small></b><b>${r.originalitySignals.uniqueWordRatio}%<small>Unique-word ratio</small></b></div><h3>Internal similarity matches</h3><div class="p10-search-results">${r.topMatches.map(m=>`<article><b>${escapeHtml(m.title)}</b><span>${m.similarity}% similarity · ${escapeHtml(m.subject)}</span></article>`).join('')||'<p class="empty-note">No internal match.</p>'}</div><div class="phase78-suggestions"><h3>Responsible-use note</h3><ul>${r.recommendations.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div>`);}
function factualStatusBadge(status){const key=String(status||'').replace(/[^a-z]+/gi,'-').toLowerCase();return `<span class="fact-status ${key}">${escapeHtml(status)}</span>`;}
function renderFactual(r){
  const claims=(r.claims||[]).map((c)=>`<article class="fact-claim ${escapeHtml(c.status)}"><div class="fact-claim-head"><b>${escapeHtml(c.id)}</b>${factualStatusBadge(c.status)}<span>${Number(c.confidence||0)}% confidence</span></div><p>${escapeHtml(c.claim)}</p><small>${escapeHtml(c.rationale||'')}</small>${c.temporalWarnings?.length?`<div class="fact-warning">${c.temporalWarnings.map(x=>`⚠ ${escapeHtml(x)}`).join('<br>')}</div>`:''}<div class="fact-evidence">${(c.evidence||[]).map(e=>`<details><summary>${escapeHtml(e.sourceName)} · ${Number(e.score||0)}% match</summary><p>${escapeHtml(e.excerpt)}</p></details>`).join('')||'<em>No supporting evidence found.</em>'}</div></article>`).join('');
  p10out(`<div class="p10-result-head"><div><span>Claim-Level Factual Verification</span><h2>${escapeHtml(r.overallStatus)}</h2></div><b>${Number(r.overallScore||0)}/100</b></div><div class="p9-mini-stats"><b>${Number(r.coverage||0)}%<small>Source coverage</small></b><b>${Number(r.averageConfidence||0)}%<small>Avg. confidence</small></b><b>${Number(r.summary?.unsupported||0)}<small>Unsupported</small></b><b>${Number(r.summary?.syllabusSourceGaps||0)}<small>Syllabus gaps</small></b></div><div class="p10-safety-checks">${Object.entries(r.checks||{}).map(([k,v])=>`<span class="${v?'warn':'ok'}">${v?'⚠':'✓'} ${escapeHtml(k.replaceAll(/([A-Z])/g,' $1'))}</span>`).join('')}</div><div class="fact-claims">${claims||'<p class="empty-note">No factual claims detected.</p>'}</div><div class="phase78-suggestions"><h3>Required action</h3><ul>${(r.recommendations||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div>`);
}
function renderSafety(r){p10out(`<div class="p10-result-head"><div><span>AI Safety & Review</span><h2>${escapeHtml(r.status)}</h2></div><b>${r.score}/100 risk</b></div><div class="p10-safety-checks">${Object.entries(r.checks).map(([k,v])=>`<span class="${v?'warn':'ok'}">${v?'⚠':'✓'} ${escapeHtml(k.replaceAll(/([A-Z])/g,' $1'))}</span>`).join('')}</div><div class="p10-findings">${r.findings.length?r.findings.map(f=>`<article class="${f.severity}"><b>${escapeHtml(f.type)}</b><p>${escapeHtml(f.message)}</p></article>`).join(''):'<p class="empty-note">No major rule-based finding.</p>'}</div>${r.factualVerification?`<h3>Claim verification summary</h3><div class="p9-mini-stats"><b>${r.factualVerification.overallScore}/100<small>Verification score</small></b><b>${r.factualVerification.coverage}%<small>Source coverage</small></b><b>${r.factualVerification.summary.unsupported}<small>Unsupported</small></b><b>${r.factualVerification.summary.lowConfidence}<small>Low confidence</small></b></div>`:''}<div class="phase78-suggestions"><h3>Required review</h3><ul>${r.recommendations.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div>${r.factualVerification?'<button id="btn-open-factual-details" class="secondary-ai-btn">Open claim-by-claim evidence</button>':''}`);if(r.factualVerification)document.getElementById('btn-open-factual-details').onclick=()=>renderFactual(r.factualVerification);}
function renderSearch(d){p10out(`<div class="p10-result-head"><div><span>Semantic Smart Search</span><h2>Results for “${escapeHtml(d.query)}”</h2></div><b>${escapeHtml(d.mode)}</b></div><p class="recent-meta">Expanded context: ${escapeHtml(d.expandedQuery)}</p><div class="p10-search-results">${d.results.length?d.results.map(r=>`<article><div><span>${escapeHtml(r.type)} · ${escapeHtml(r.subject)}</span><h3>${escapeHtml(r.topic)}</h3><p>${escapeHtml(r.excerpt)}</p></div><b>${r.score}%</b><button data-p10-view="${r.id}">View</button></article>`).join(''):'<p class="empty-note">No matching resource found.</p>'}</div>`);document.querySelectorAll('[data-p10-view]').forEach(b=>b.onclick=(ev)=>{ev.preventDefault();ev.stopPropagation();console.debug('[p10-search] opening resource',b.dataset.p10View);openModal(b.dataset.p10View);});}
async function renderIntelligence(){p10ResourceOptions();if(p10Loaded)return;p10Loaded=true;document.getElementById('btn-p10-voice').onclick=async()=>{try{p10status('Creating voice explanation…');const d=await apiP10VoiceScript({resourceId:document.getElementById('p10-resource').value||undefined,text:document.getElementById('p10-text').value,topic:document.getElementById('p10-topic').value,language:document.getElementById('p10-language').value,style:document.getElementById('p10-voice-style').value});renderVoice(d.output);p10status('Voice explanation ready.');}catch(e){p10status(e.message,true)}};document.getElementById('btn-p10-video').onclick=async()=>{try{p10status('Building scene-by-scene academic script…');const d=await apiP10Video({topic:document.getElementById('p10-topic').value,subject:document.getElementById('p10-subject').value,format:document.getElementById('p10-video-format').value,language:document.getElementById('p10-language').value,context:document.getElementById('p10-text').value});renderVideo(d.output);p10status('Video script ready.');}catch(e){p10status(e.message,true)}};document.getElementById('btn-p10-diagram').onclick=async()=>{try{p10status('Planning and rendering diagram…');const d=await apiP10Diagram({type:document.getElementById('p10-diagram-type').value,topic:document.getElementById('p10-topic').value,context:document.getElementById('p10-text').value});renderDiagram(d);p10status('Diagram ready.');}catch(e){p10status(e.message,true)}};
document.getElementById('btn-p10-chart').onclick=async()=>{try{p10status('Planning and rendering chart…');const d=await apiP10Chart({type:document.getElementById('p10-chart-type').value,topic:document.getElementById('p10-topic').value,context:document.getElementById('p10-text').value});renderChart(d);p10status('Chart ready.');}catch(e){p10status(e.message,true)}};
document.getElementById('btn-p10-smart-table').onclick=async()=>{try{p10status('Cleaning table and finding key rows…');const d=await apiP10SmartTable({rawText:document.getElementById('p10-text').value,context:document.getElementById('p10-topic').value});renderSmartTable(d);p10status('Smart table ready.');}catch(e){p10status(e.message,true)}};
document.getElementById('btn-p10-web-search').onclick=async()=>{try{p10status('Searching Wikipedia…');const d=await apiWebSearch({topic:document.getElementById('p10-topic').value});renderWebSearch(d);p10status('Search complete.');}catch(e){p10status(e.message,true)}};
document.getElementById('btn-p10-image-search').onclick=async()=>{try{p10status('Searching Wikimedia Commons…');const d=await apiImageSearch({topic:document.getElementById('p10-topic').value});renderImageResults(d,'Image Finder');p10status('Search complete.');}catch(e){p10status(e.message,true)}};
document.getElementById('btn-p10-illustration-search').onclick=async()=>{try{p10status('Searching for illustrations…');const d=await apiIllustrationSearch({topic:document.getElementById('p10-topic').value});renderImageResults(d,'Illustration Finder');p10status('Search complete.');}catch(e){p10status(e.message,true)}};
document.getElementById('btn-p10-infographic').onclick=async()=>{try{p10status('Building infographic…');const d=await apiGenerateInfographic({topic:document.getElementById('p10-topic').value,context:document.getElementById('p10-text').value});renderInfographic(d);p10status('Infographic ready.');}catch(e){p10status(e.message,true)}};document.getElementById('btn-p10-risk').onclick=async()=>{try{p10status('Comparing assignment with internal resource library…');const d=await apiP10Similarity({text:document.getElementById('p10-risk-text').value});renderRisk(d.report);p10status('Risk analysis complete.');}catch(e){p10status(e.message,true)}};document.getElementById('p10-safety-resource').addEventListener('change',()=>{const resource=resources.find(x=>String(x._id)===String(document.getElementById('p10-safety-resource').value));const select=document.getElementById('p10-fact-syllabus');const linked=resource?.syllabusId||resource?.syllabus;if(linked&&[...select.options].some(o=>String(o.value)===String(linked)))select.value=String(linked);});document.getElementById('btn-p10-factual').onclick=async()=>{try{p10status('Extracting factual claims and matching syllabus evidence…');const d=await apiP10Factual({resourceId:document.getElementById('p10-safety-resource').value||undefined,text:document.getElementById('p10-safety-text').value,syllabusId:document.getElementById('p10-fact-syllabus').value||undefined,includeInternalReferences:document.getElementById('p10-include-internal').checked});renderFactual(d.report);p10status('Claim-level factual verification complete.');}catch(e){p10status(e.message,true)}};document.getElementById('btn-p10-safety').onclick=async()=>{try{p10status('Running full safety and claim-level source verification…');const d=await apiP10Safety({resourceId:document.getElementById('p10-safety-resource').value||undefined,text:document.getElementById('p10-safety-text').value,syllabusId:document.getElementById('p10-fact-syllabus').value||undefined,includeInternalReferences:document.getElementById('p10-include-internal').checked});renderSafety(d.report);p10status('Full safety review complete.');}catch(e){p10status(e.message,true)}};document.getElementById('btn-p10-search').onclick=async()=>{try{p10status('Running semantic + expanded-keyword search…');const d=await apiP10Search(document.getElementById('p10-search').value);renderSearch(d);p10status(`${d.results.length} result(s) found.`);}catch(e){p10status(e.message,true)}};document.getElementById('p10-search').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('btn-p10-search').click()});}
